myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("pollApp.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

myProject/pollApp/urls.py
from django.urls import path

from . import views

app_name = "pollApp"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

myProject/pollApp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean = True,
        ordering = "pub_date",
        description = "Published Recently"
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

myProject/pollApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "question_lists"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
    
    

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return redirect(reverse('pollApp:results', args=(question.id,)))

myProject/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>
    {% block title %}{% endblock title %}
  </title>
  <link rel="stylesheet" href="{% static 'pollApp/style.css' %}" />
</head>

<body>
  <div class="container">
    <div class="row">
      {% block content %}{% endblock content %}
    </div>
  </div>
</body>

myProject/templates/polls/detail.html
{% extends "./base.html" %} 

{% block title %}Detail{% endblock title %} 

{% block content %}

<h1>Question Detail</h1>

<form action="{% url 'pollApp:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>
      <h1>{{ question.question_text }}</h1>
    </legend>
    {% if error_message %}
      <p>
        <strong>{{ error_message }}</strong>
      </p>
    {% endif %}
    {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
      <br />
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote" />
</form>

<p>
  <a href="{% url 'pollApp:index' %}">Back to Question List</a>
</p>

{% endblock content %}

myProject/templates/polls/index.html
{% extends "./base.html" %} 

{% block title %}Home{% endblock title %} 

{% block content %}
<h1>Lastest Question List</h1>

{% if question_lists %}
<ul>
  {% for question in question_lists %}
  <li>
    <a href="{% url 'pollApp:detail' question.id %}">
      {{question.question_text}}
    </a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} 

{% endblock content %}

myProject/templates/polls/results.html
{% extends "./base.html" %} 

{% block title %}Detail{% endblock title %} 

{% block content %}

<h1>{{question.question_text}}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{choice.choice_text}} -- {{choice.votes }} vote{{choice.votes|pluralize}}
  </li>
  {% endfor %}
</ul>

<a href="{% url 'pollApp:detail' question.id %}">Vote again?</a>

{% endblock content %}